version: '2.4'

services:
  postgres:
    image: mdillon/postgis:11-alpine
    volumes:
      - ./data:/data
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: spiritx
      POSTGRES_PASSWORD: password

volumes:
  postgres:
